
export const robot = 'robot';

// actions
export const ROBOT_GET_CARDS = 'ROBOT_GET_CARDS';

export const ROBOT_SET_ACTIVE = 'ROBOT_SET_ACTIVE';
export const ROBOT_SET_UNACTIVE = 'ROBOT_SET_UNACTIVE';

export const ROBOT_SET_ATACK_ACTION = 'ROBOT_SET_ATACK_ACTION';
export const ROBOT_SET_DEFEND_ACTION = 'ROBOT_SET_DEFEND_ACTION';

export const ROBOT_PUT_CARD = 'ROBOT_PUT_CARD';

export const ROBOT_WILL_TAKE_ALL_CARDS = 'ROBOT_WILL_TAKE_ALL_CARDS';
export const ROBOT_TAKE_ALL_CARDS = 'ROBOT_TAKE_ALL_CARDS';
